# Generated by Django 2.1.7 on 2019-04-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_country'),
        ('account', '0004_auto_20190409_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(to='orders.Order'),
        ),
    ]
