# Generated by Django 2.1.7 on 2019-04-24 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_data_forwards(apps, schema_editor):
    User = apps.get_model("account", "User")
    Address = apps.get_model("account", "Address")
    for user in User.objects.all():
        if user.first_name:
            address = Address()
            address.name = f"{user.first_name} {user.last_name}"
            address.phone = user.phone
            address.street = user.street
            address.city = user.city
            address.province = user.province
            address.postal_code = user.code
            address.country = user.country
            address.user = user
            address.save()


def move_data_backwards(apps, schema_editor):
    User = apps.get_model("account", "User")
    Address = apps.get_model("account", "Address")
    for user in User.object.all():
        if user.addresses.first().exists():
            address = user.addresses.first()
            user.first_name = str(address.name).partition(" ")[0]
            user.last_name = str(address.name).partition(" ")[-1]
            user.phone = address.phone
            user.street = address.street
            user.city = address.city
            user.province = address.province
            user.code = address.postal_code
            user.country = address.country


class Migration(migrations.Migration):

    dependencies = [("account", "0005_user_orders")]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100, null=True)),
                ("street", models.CharField(max_length=100, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(max_length=100, null=True)),
                ("country", models.CharField(max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(move_data_forwards, move_data_backwards),
    ]
