# Generated by Django 2.1.7 on 2019-05-13 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# shop.migrations.0006_auto_20190415_1756
# shop.migrations.0011_productimage
# shop.migrations.0015_auto_20190510_2013
def product_image_rename_fields_forwards(apps, schema_editor):
    apps.get_model("shop", "ProductImage")


def product_image_rename_fields_backwards(apps, schema_editor):
    apps.get_model("shop", "ProductImage")

def comment_rename_fields_forwards(apps, schema_editor):
    Comment = apps.get_model("shop", "Comment")
    Comment.objects.update(is_active=F("active"), date_created=F("created"))


def comment_rename_fields_backwards(apps, schema_editor):
    Comment = apps.get_model("shop", "Comment")
    Comment.objects.update(active=F("is_active"), created=F("date_created"))


def rename_fields_forwards_15(apps, schema_editor):
    ProductImage = apps.get_model("shop", "ProductImage")
    Product = apps.get_model("shop", "Product")
    for p in Product.objects.all():
        ProductImage.objects.create(product=p, image=p.image)


def rename_fields_backwards_15(apps, schema_editor):
    ProductImage = apps.get_model("shop", "ProductImage")
    for pi in ProductImage.objects.all():
        pi.product.image = pi.image

class Migration(migrations.Migration):

    replaces = [('shop', '0001_initial'), ('shop', '0002_auto_20190327_1934'), ('shop', '0003_comment'), ('shop', '0004_auto_20190404_1652'), ('shop', '0005_auto_20190415_1756'), ('shop', '0006_auto_20190415_1756'), ('shop', '0007_auto_20190415_1818'), ('shop', '0008_auto_20190415_1823'), ('shop', '0009_auto_20190416_1857'), ('shop', '0005_auto_20190415_1734'), ('shop', '0010_merge_20190422_2204'), ('shop', '0011_productimage'), ('shop', '0012_auto_20190508_1932'), ('shop', '0011_auto_20190508_1912'), ('shop', '0013_merge_20190508_2033'), ('shop', '0014_like'), ('shop', '0015_auto_20190510_2013')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('total_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('count_rating', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.RunPython(
            code=comment_rename_fields_forwards,
            reverse_code=comment_rename_fields_backwards,
        ),
        migrations.RenameField(
            model_name='Comment',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_created']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Category'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product')),
            ],
        ),
        migrations.RunPython(
            code=product_image_rename_fields_forwards,
            reverse_code=product_image_rename_fields_backwards,
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            code=rename_fields_forwards_15,
            reverse_code=rename_fields_backwards_15,
        ),
    ]
