# Generated by Django 2.1.7 on 2019-04-15 15:56

from django.db import migrations
from django.db.models import F


def rename_fields_forwards(apps, schema_editor):
    Comment = apps.get_model("shop", "Comment")
    Comment.objects.update(is_active=F("active"), date_created=F("created"))


def rename_fields_backwards(apps, schema_editor):
    Comment = apps.get_model("shop", "Comment")
    Comment.objects.update(active=F("is_active"), created=F("date_created"))


class Migration(migrations.Migration):

    dependencies = [("shop", "0005_auto_20190415_1756")]

    operations = [
        migrations.RunPython(rename_fields_forwards, rename_fields_backwards),
        migrations.RenameField("Comment", "updated", "date_updated"),
    ]
