# Generated by Django 2.1.7 on 2019-04-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190415_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
