# Generated by Django 2.1.7 on 2019-04-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190415_1734'),
        ('shop', '0009_auto_20190416_1857'),
    ]

    operations = [
    ]
