# Generated by Django 2.1.7 on 2019-05-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190508_1912'),
        ('shop', '0012_auto_20190508_1932'),
    ]

    operations = [
    ]
