# Generated by Django 2.1.7 on 2019-05-10 18:13

from django.db import migrations, models
import django.db.models.deletion


def rename_fields_forwards(apps, schema_editor):
    ProductImage = apps.get_model("shop", "ProductImage")
    Product = apps.get_model("shop", "Product")
    for p in Product.objects.all():
        ProductImage.objects.create(product=p, image=p.image)


def rename_fields_backwards(apps, schema_editor):
    ProductImage = apps.get_model("shop", "ProductImage")
    for pi in ProductImage.objects.all():
        pi.product.image = pi.image


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_like'),
    ]

    operations = [
        migrations.RunPython(rename_fields_forwards, rename_fields_backwards),
    ]
