# Generated by Django 2.1.7 on 2019-05-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20190513_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdiscount',
            old_name='discount_procent',
            new_name='discount_percent',
        ),
    ]
