# Generated by Django 2.1.7 on 2019-05-19 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20190519_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='discounts', to='shop.Category')),
            ],
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='category_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.CategoryDiscount'),
        ),
    ]
