# Generated by Django 2.1.7 on 2019-05-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_product_image'),
        ('shop', '0017_auto_20190513_2035'),
    ]

    operations = [
    ]
